### ISSUE TITLE
zaw fan-made campaign download-url

### ISSUE THREAD

**Issue by derornos** [zzorba/arkham-cards-data#381]
ko/zaw/campaign.po

I added the following content to the bottom of the file. 

msgid "https://mysteriouschanting.wordpress.com/2020/10/30/alice-in-wonderland-campaign/"
msgstr "https://cafe.naver.com/arkhamfiles/2254"

but it doesn't working. 
(Links to English original page only.)

※ android, arkhamcards beta ver 21.06.13.

**Comment by zzorba** [comment]
I will have to add this in manually, will do.

**Comment by zzorba** [comment]
Pushed an update for this to the repo (will be released in next few days), because it's not *really* a translation string, I'll put these links in the original source files.  

I've added the link you specified here to the zaw/campaign.json file under a new `ko` tag.
