### ISSUE TITLE
What is the version of Dark Matter?

### ISSUE THREAD

**Issue by derornos** [zzorba/arkham-cards-data#469]
I'm curious about the version of the current Dark Matter.
It was released as a final version on August 10th.
Has it been changed?

thx for your efforts. 
: )

**Comment by zzorba** [comment]
Yes! So the campaign in the app was always a bit ahead of the official release, and Axolotl sent me edits to make to update to the latest.

As far as I can tell, the only major change (from the original app release) was removing some parenthetical during setup and correcting a couple small typos.  I took the time to update the Korean translations to remove the parentheticals from your translations as well, so I believe we are good to go.

**Comment by derornos** [comment]
"Echoes of the Past" (zdm/00198) issue!

Wasn't this card deleted? 

plz, re-check the final version of  dm campaign.
(there may be something other than this card issue.)


[related json list]

zdm/introspection.json
line 198-249

cards/zdm.json
line 159-173

**Comment by zzorba** [comment]
Yeah, I took a list of updates from the designer, looks like this one got overlooked.  Will update the app to remove these steps.

**Comment by derornos** [comment]
okay! thx XD
