### ISSUE TITLE
Carcosa token management - German (and maybe more)

### ISSUE THREAD

**Issue by norbertspiess** [zzorba/arkham-cards-data#812]
### Affected campaign
Path to Carcosa / Return to Path to Carcosa

### What
Wrong instructions for chaos bag manipulation between scenarios (and possibly agendas in Curtain Call as well). 

### App version
3.2.3

### Affected languages
DE (possibly more, EN & ES are fine)

### Details
I get the impression that the German version of the Carcosa campaign is sadly riddled with bugs. Regarding the various token manipulations going on.
Everything kind of starts with "The Last King" as the first scenario with the heavy token manipulation. Where, depending on the resolution, the chaos bag is changed for the upcoming scenarios (https://images-cdn.fantasyflightgames.com/filer_public/0d/72/0d72fab8-2e2c-4760-807d-f36a83130fe7/path_to_carcosa_campaign_guide_eng_final_release.pdf, page 7 on resolution 2 & 3).

E.g. with **_Resolution 3_**, the App (in English / Spanish) states: _add 1 token of each_. Whereas the German translation says: _add 2 cultist tokens_.

##### english
![image](https://user-images.githubusercontent.com/29440287/188719863-fea39f5a-29cf-4350-9bf2-020713f6c18a.png)

##### german
![image](https://user-images.githubusercontent.com/29440287/188721733-839c34c6-40e7-4210-b69b-f2d7cf663b54.png)

I fear this ripples through the whole campaign, with agendas in Curtain Call and other scenarios.

I had a look at [the campaign json](https://github.com/zzorba/arkham-cards-data/blob/master/campaigns/ptc/echoes_of_the_past.json) and [the german translation file](https://github.com/zzorba/arkham-cards-data/blob/master/i18n/de/campaigns/ptc/the_last_king.po) and couldn't find the mismatch. The campaign is correctly set up in the json and I can't even find the related text phrase "Dann werden 2 [cultist]-Marker dem Chaosbeutel hinzugefügt." anywhere in the repository.

Something more sinister, ancient and evil is going on ..

**Comment by zzorba** [comment]
Sorry about that -- the logic will always be correct behind the scenes (i.e the digital chaos bag will be correct), but I understand the frustration.  

If you find issues like this, I can correct them.

So the bad string is here -- https://github.com/zzorba/arkham-cards-data/blob/master/i18n/de/campaigns/ptc/echoes_of_the_past.po#L86 The way that the translation works is, entire 'paragraphs' basically, so even though the string is correct somewhere else, in this particular phrasing they wrote the wrong thing.

If you give me the corrected string, I can make an update here.

**Comment by zzorba** [comment]
Fixed https://github.com/zzorba/arkham-cards-data/commit/316c60d663781624a01798d03679e4cba1d0bbb6

So the confusing thing is, to save translators time, I only make them translate each "phrase" once.  And it doesn't always end up chronologically first -- so sometimes a phrase from Scenario 2 will end up in Scenario 4 or 5 (or sometimes even in a different campaign).

In this case, the same phrase shows up in Echoes of the Past as well.
