### ISSUE TITLE
Alice in Wonderland: Scenario 1 - Arkham in Wonderland - Resolution bug

### ISSUE THREAD

**Issue by stefanesterer** [zzorba/arkham-cards-data#888]
Hi!

It seems that there is a bug in the resolution step of the first scenario of the fan campaign "Alice in Wonderland". 
The campaign guide (downloaded from arkham central http://arkhamcentral.com/index.php/alice-in-wonderland-campaign/) looks like that:

![image](https://user-images.githubusercontent.com/1726277/199288411-7ce25434-04dc-40e6-b31d-c161bb396b3f.png)

So if I read this correctly, if at least one investigator was defeated and NO investigator resigned, the app should show me the first option "As you wonder if this..." and the next step would be resolution 1.

The app instead does this:

![image](https://user-images.githubusercontent.com/1726277/199288987-183d6095-a18c-4b51-873d-ff6ae673bf93.png)

I suspect this is because there is a bug somwhere here:
https://github.com/zzorba/arkham-cards-data/blob/master/campaigns/zaw/arkham_in_wonderland.json#L85

Do I read this correctly or did I misunderstand something?

thx for all the great work!

**Comment by stefanesterer** [comment]
Looking a little closer, I think just swapping the steps texts of no_resigned_story (https://github.com/zzorba/arkham-cards-data/blob/master/campaigns/zaw/arkham_in_wonderland.json#L108) and resigned_story (https://github.com/zzorba/arkham-cards-data/blob/master/campaigns/zaw/arkham_in_wonderland.json#L113) should fix the problem. Am I right?

**Comment by zzorba** [comment]
Yeah, looks like I flipped them in the branch, I have set it up correctly now and will fix this in the next release.

Thanks for the bug report!

<img width="505" alt="Screen Shot 2022-11-01 at 4 54 32 PM" src="https://user-images.githubusercontent.com/1091291/199339015-2a9a875c-14e4-4aa4-b616-cd412e7688b9.png">
