### ISSUE TITLE
Names on Travel Map

### ISSUE THREAD

**Issue by fafranco82** [zzorba/arkham-cards-data#912]
First of all, I want to thank you for your effort on translate everything in the travel map, not only the name of cities... In the Spanish version, for example, only city names are translated, but continents, oceans and seas remain untranslated :(

I detect an error in the labels used for oceans. Atlantic Ocean is split in two different labels ("A T L A N T I C" y "O C E A N") that I need to inversed in translation, so "A T L A N T I C" => "O C É A N O" and "O C E A N" => "A T L Á N T I C O", because Atlantic Ocean is Océano Atlántico in Spanish... At first, this should not be a problem... except that Artict Ocean has two labels too, "A R T I C T" and it shares the label "O C E A N" with the Atlantic Ocean... so in my translated map, without translating "ARTICT" yet,  it can be read "ARTICT ATLÁNTICO"... 

I don't know what can be the best solution to this. Maybe leaving all of these toponymns untranslated... but it would be a pity to waste your amazing work with the map :(

**Comment by zzorba** [comment]
Thanks for letting me know, I'll see about finding a way to fix this.

**Comment by zzorba** [comment]
Okay, reworked it to make them complete.

I do worry that the positioning logic is going to be awkward, but we do have some control over it with spaces and tabs and whatnot (but it requires a lot of trial and error).

**Comment by zzorba** [comment]
Actually, I'm going to push an update shortly that moves from tabs to spaces.  Turns out tabs don't work very well on Android (or at least they aren't consistent), while spaces are.
