### ISSUE TITLE
TSK error report (dead and gone)

### ISSUE THREAD

**Issue by elkeinkrad** [zzorba/arkham-cards-data#968]
The condition is "30 **or** fewer time has passed" as following.

https://github.com/zzorba/arkham-cards-data/blob/2038abc39eedf094b24c5c3f4e7a0d040d501a3f/campaigns/tskc/09_dead_and_gone.json#L95

In code, the condition is implemented as fewer than 30 time has passed, as I know.
https://github.com/zzorba/arkham-cards-data/blob/2038abc39eedf094b24c5c3f4e7a0d040d501a3f/campaigns/tskc/09_dead_and_gone.json#L106-L121

It seems the condition excludes 30 time.

**Comment by zzorba** [comment]
<img width="609" alt="Screen Shot 2023-01-12 at 10 13 57 AM" src="https://user-images.githubusercontent.com/1091291/212104620-44c85513-ad60-4644-845c-0a445c62b290.png">


I think it is correct here?  The calculation is basically (opA - opB), and then checks if the result is negative (-1) equal (0), or positive (1).

In this case (time - 30) and the two "true" conditions are negative (time < 30) or equal (time = 30).

Did you observe it doing the incorrect thing in the app?

**Comment by elkeinkrad** [comment]
I re-check about that and it seems my mistake. I thought I arrived Roma at time 30 but skip to 7, but I retry in app work app. sorry to bordering you.
