### ISSUE TITLE
Merge request permission

### ISSUE THREAD

**Issue by romstheking** [zzorba/arkham-cards-data#994]
Hi
I want to push and create a merge request (french translation for TSK)
I get this all the time : remote: Permission to zzorba/arkham-cards-data.git denied to romstheking.
fatal: unable to access 'https://github.com/zzorba/arkham-cards-data/': The requested URL returned error: 403
Pushing to https://github.com/zzorba/arkham-cards-data

Can u tell me how to push it ? 
Thanks

**Comment by zzorba** [comment]
Yeah, so the general way is that you want to fork the repository, and then push your changes there. GitHub will make a UI button on this repository then to merge your change from a branch back here.

You can also email me the files at ArkhamCards at Gmail

**Comment by romstheking** [comment]
Okay
I tried to push a branch from your repo at first...

The fork way did the job, i have push with success the merge request
Thanks.
You can close this issue
